---
title: "Bank Analysis"
date:  "Last complied on `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document: 
  
    
    theme: sandstone
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE, 
                      warning = FALSE,
                      message = FALSE)
```

```{r}
library(tidyverse)
df<-read.csv("I:\\Classes\\ISA 633\\Homework\\Homework 2 New\\BankData.csv")
table(df$education)
```

## Secondary Education

```{R}
secondary<-df %>% filter(education=="secondary")
secondary%>% group_by(version, y) %>% summarise(n=n()) %>% mutate(freq=n/sum(n))

```


```{r}
prop.test(x=c(1253, 1197), n=c(10403+1253, 10349+1197))

```

## Age

```{r}
df %>% group_by(version) %>% summarize("mean sales"=mean(age), "std sales"=sd(age),"count"= n())

t.test(age~version, data=df)

```


## Job

```{r}
table(df$job)
blue.collar<-df %>% filter(job=="blue-collar")
blue.collar %>% group_by(version, y) %>% summarise(n=n()) %>% mutate(freq=n/sum(n))
```


```{r}

prop.test(x=c(336, 372), n=c(4539+ 336, 4485+372))

```